name: My First Pipeline

on:
  push:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Show current directory
        run: pwd

      - name: Show files
        run: ls -la

      - name: Status
        run: echo "CI is working"
  
  second-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo "This is another job"